### ISSUE TITLE
Last update broken all my thermostat

### ISSUE THREAD

**Issue by devildant** [litinoveweedle/hass-template-climate#12]
### The problem

hello, 

with the last update when i change the mode, fan speed, swing nothing work. the automation are not call

```
- platform: climate_template
  name: Climatisation Salon Climate Template
  unique_id: climatisation_salon_climate_template
  # unique id not working but mendatory for working
  icon_template: mdi:air-conditioner
  mode_action: "parallel"
  max_action: 10
  hvac_modes:
    - "dry"
    - "off"
    - "cool"
    - "fan_only"
  fan_modes:
    - "Auto"
    - "20%"
    - "40%"
    - "60%"
    - "80%"
    - "100%"
    - "Silencieux"
    - "Turbo"
  swing_modes:
    - "Position 1"
    - "Position 2"
    - "Position 3"
    - "Position 4"
    - "Position 5"
    - "Activé"
    - "Désactivé"
  min_temp: 16
  max_temp: 31
  availability_template: "{{ states('switch.localtuya_integration_climatisation_salon_power') in ['on', 'off'] }}"
  current_temperature_template: "{{ states('sensor.localtuya_integration_climatisation_salon_temperature_courante') }}"
  set_hvac_mode:
    - service: automation.trigger
      data:
        skip_condition: false
      target:
        entity_id: automation.0009_climate_template_climatisation_salon_set_hvac_mode
  set_fan_mode:
    - service: automation.trigger
      data:
        skip_condition: false
      target:
        entity_id: automation.0009_climate_template_climatisation_salon_set_fan_mode
  set_swing_mode:
    - service: automation.trigger
      data:
        skip_condition: false
      target:
        entity_id: automation.0009_climate_template_climatisation_salon_set_swing_mode
  set_temperature:
    - service: automation.trigger
      data:
        skip_condition: false
      target:
        entity_id: automation.0009_climate_template_climatisation_salon_set_temperature
```

### What version of Template Climate has the issue?

0.7.0

### What version of Home Assistant are you running?

12.2

### What type of installation are you running?

Home Assistant OS

**Comment by devildant** [comment]
if i rollback to 0.6.4 it's work perfectly

**Comment by devildant** [comment]
well the automation is well executed but all my conditions are false, I don't understand what changed between the two versions of the plugin

**Comment by devildant** [comment]
after debugging

here is my logic

tuya cloud => change detected => boolean set to true and calls my climate template to change the value

my climate template => if boolean activated do nothing, otherwise call tuya cloud to change the value

In 0.6.4
1) action on my climate template

2) climate template call tuya cloud

3) tuya cloud sets the boolean to true and calls climate template

4) my climate template receives the command and ignores the command because the boolean is activated and sets it to false

In 0.7.0:
1) action on my climate template

2) climate template call tuya cloud

3) tuya cloud sets the boolean to true and calls climate template

4) my climate template does not receive the command and the boolean remains true

5) new action on my climate template

6) nothing happens because the command was ignored because the boolean is true

To make it operational again, I removed the boolean protection and compared the data between my climate model with tuya cloud to determine whether or not I should perform the action.

it works.

I just hope it doesn't change again :p

**Comment by litinoveweedle** [comment]
Hi, I am sorry to hear this. Would you please be able to switch debug mode:

```
logger:
  default: warning
  logs:
    custom_components.climate_template.climate: debug
```

and try to execute action which is causing issue? I added a lot of debug messages, but there is also changed logic to prevent looping from template to action - see #9 .

This means, it the attributes is not changed (i.e. temperature) from the internal entity held state, than action is not executed. You will see this from the debug logs.

If I understand correctly, you use thermostat card in HA GUI to set some devices using automation. So there are no templates to feed back the status of given attribute to entity. It that case, if internal attribute of the entity is already at some value change it to the same value will not re-trigger corresponding action. I can probably improve on the logic in #9 and use it only if the template for attribute is also configured.

Would you be able to test it (manually replace climate.py) on you HA?

**Comment by litinoveweedle** [comment]
You can try the proposed fix easily by replacing line number 1067 in your climate.py

`            if getattr(self, "_attr_" + attr) == attributes[attr]["value"]:`

by (EDITED! please use this version)

`            if getattr(self, "_template_" + attr) and getattr(self, "_attr_" + attr) == attributes[attr]["value"]:`

Then enable debug, restart HA an test it.

**Comment by devildant** [comment]
Ha sorry if I wasn't clear in my last message.
I solved my problem by changing my logic (deleting the booleans and adding a some checks in my automations, to check that the thermostat does not already have the requested modification.

I just hope you don't change the logic again :)

I left the issue open to notify you of the problem I encountered. in case another user encounters a similar problem

**Comment by litinoveweedle** [comment]
Hello,

thank you for reply, I am glad that you solve the issue.

> I solved my problem by changing my logic (deleting the booleans and adding a some checks in my automations, to check that the thermostat does not already have the requested modification.

Just to be clear, the original aim of the logic changes was to fix 'Already running' error (being triggered by both template and action referring to same entity and causing loop). But I wanted also to improve climate_template to run without further external logic (for example using automations to check and set state of the climate_template entity), while keeping as much backward compatibility as possible.

To be able to achieve this I need you help. It is important to me to understand how other people using the climate_template. Without such understanding I can't prevent breaking the logic. While I can not promise to make breaking changes in the future, those shall be for integration improvements and not by accident.

I unfortunately still to not completely understand your setup, can you please describe it so I would get it? :-) In the original description I was especially confused by the 'boolean' logic. Can you can please try to describe how you interconnect your Tuya thermostat to the climate_template. Do you use any automation to check and set climate_template using services? Maybe to include full configuration setup?

While I am asking is also to improve documentation to include tested usage. I really think, that your  intended usage is similar to mine, but you use different implementation. In my case, I have a gas boiler, which is controlled by Home assistant inputs (like number to set the desired target_temperature and select or switch to select operation mode - heat, off etc.). If I will set temperature or working mode on the physical boiler thermostat on my wall, those inputs in HA will after some time also change, to reflect the current boiler settings. To use this together with the climate_template it is not required to have any additional automation logic: If I will change target_temperature or hvac_mode in the HA, boiler is set using changed input value. If boiler is set directly using hardware thermostat, it reports changes via updates of the input back to HA and climate_entity is updated to reflect those new values using templates. If you Tuya thermostat provides sensors to reflect its current state, those can be use as a inputs directly in the climate_template templates as well (instead of inputs as in my case).

My example:

```
  - platform: climate_template
    name: "Heating DHW"
    unique_id: "climate_template_heating_dhw"
    mode_action: "queued"
    max_action: 3
    hvac_modes:
      - "heat"
      - "off"
    min_temp: 10
    max_temp: 60
    temp_step: 1
    availability_template: "{{ states('sensor.thrs19_dhw_status') not in [ 'unavailable', 'unknown', 'none' ] and states('switch.thrs19_dhw_operating_mode') not in [ 'unavailable', 'unknown', 'none' ] and states('number.thrs19_dhw_temperature_nominal_setpoint') not in [ 'unavailable', 'unknown', 'none' ] and states('number.thrs19_dhw_temperature_nominal_setpoint') not in [ 'unavailable', 'unknown', 'none' ] }}"
    current_temperature_template: "{{ states('sensor.thrs19_dhw_temperature_actual_value_top_b3') }}"
    hvac_mode_template: "{% if states('switch.thrs19_dhw_operating_mode') == 'on' %}heat{% else %}off{% endif %}"
    target_temperature_template: "{{ states('number.thrs19_dhw_temperature_nominal_setpoint') }}"
    hvac_action_template: "{% if states('switch.thrs19_dhw_operating_mode') != 'on' %}off{% elif states('sensor.thrs19_dhw_status') in [ 'Push, nominal setpoint', 'Charging, nominal setpoint' ] %}heating{% else %}idle{% endif %}"
    set_temperature:
      - service: number.set_value
        target:
          entity_id: number.thrs19_dhw_temperature_nominal_setpoint
        data:  
          value: "{{ temperature }}"
      - delay:
          milliseconds: 500
      - service: homeassistant.update_entity
        target:
          entity_id: number.thrs19_dhw_temperature_nominal_setpoint
      - delay:
          milliseconds: 500
      - condition: template
        value_template: "{{ hvac_mode is defined and (( hvac_mode == 'heat' and states('switch.thrs19_dhw_operating_mode') != 'on' ) or ( hvac_mode == 'off' and states('switch.thrs19_dhw_operating_mode') != 'off' )) }}"
      - service: switch.toggle
        target:
          entity_id: switch.thrs19_dhw_operating_mode
      - delay:
          milliseconds: 500
      - service: homeassistant.update_entity
        target:
          entity_id: switch.thrs19_dhw_operating_mode
      - delay:
          milliseconds: 500
    set_hvac_mode:
      - condition: template
        value_template: "{{ hvac_mode is defined and (( hvac_mode == 'heat' and states('switch.thrs19_dhw_operating_mode') != 'on' ) or ( hvac_mode == 'off' and states('switch.thrs19_dhw_operating_mode') != 'off' )) }}"
      - service: switch.toggle
        target:
          entity_id: switch.thrs19_dhw_operating_mode
      - delay:
          milliseconds: 500
      - service: homeassistant.update_entity
        target:
          entity_id: switch.thrs19_dhw_operating_mode
      - delay:
          milliseconds: 500 

```

**Comment by devildant** [comment]
hello, 

I can try to explain my use to you :)
I use climate template to create virtual thermostats in HA.
I have 2 use cases:
1) for heating, I use climate template to be able to control two thermostats, my heating is connected with tado, so I have two possible thermostats, either via the cloud or via homekit, except it may happen that one or the 'other is unavailable, in this case I can switch with a simple boolean which thermostat my climate template is on.

For this climate template, I bypassed the action part and I control everything via automations which monitors the climate template
(I do this because for development or debugging, I can modify without having to restart HA)

example :

```
- platform: climate_template
  name: chauffage_salon_scheduler
  unique_id: chauffage_salon_scheduler
  icon_template: mdi:home-clock
  temp_step: 0.1
  hvac_modes:
    - "off"
    - "heat"
  min_temp: 5
  max_temp: 25
  current_temperature_template: "{% if states('switch.personnal_chauffage_salon_cloud_switch') == 'on' %} {{ state_attr('climate.chauffage_salon_cloud', 'current_temperature') | float }} {% else %} {{ states('sensor.chauffage_salon_homekit_current_temperature_wrapper') | float }} {% endif %}"
  current_humidity_template: "{% if states('switch.personnal_chauffage_salon_cloud_switch') == 'on' %} {{ state_attr('climate.chauffage_salon_cloud', 'current_humidity') | float }} {% else %} {{ states('sensor.chauffage_salon_homekit_current_humidity_wrapper')  | float }} {% endif %}"
  set_hvac_mode:
    - delay: '00:00:00.001'
  set_temperature:
    - delay: '00:00:00.001'
```

Note: 
this climate model was not affected by the last update

Note 2:
the binding is unidirectional, that is to say, the climate template is master and ignores changes coming from the cloud or homekit 

2) For air conditioning, I unfortunately have no choice but I have to go through Tuya if I want to have all the functionality, however I do not use the Tuya cloud (because it cannot create a climate entity correct), but I use local tuya, to do this I mapped each action of my air conditioner with select and boolean, and I use climate template to create a thermostat in HA.
to do this I mapped each action (set temperature, swing, fan speed...) via automations (also to be able to intervene without having to restart HA)

however I also have a very limited backup solution to control my air conditioner, for this I use tado air conditioning v3, which is basically a connected infrared remote control, but the problem with this is that if I modify my air conditioner with the remote control supplied with it, I cannot retrieve the status of my air conditioner in HA.

For this I have a double binding, my climate template can send commands to local tuya, but my local tuya also sends commands to my climate template.

I am therefore obliged to manage the collisions.

this is why initially, I had created boulean which changes to true when the command comes from tuya local, in order to prevent the thermostat from sending the command to tuya local....
exemple: 

```
- platform: climate_template
  name: Climatisation Salon Climate Template
  unique_id: climatisation_salon_climate_template
  # unique id not working but mendatory for working
  icon_template: mdi:air-conditioner
#   mode_action: "parallel"
#   max_action: 10
  hvac_modes:
    - "dry"
    - "off"
    - "cool"
    - "fan_only"
  fan_modes:
    - "Auto"
    - "20%"
    - "40%"
    - "60%"
    - "80%"
    - "100%"
    - "Silencieux"
    - "Turbo"
  swing_modes:
    - "Position 1"
    - "Position 2"
    - "Position 3"
    - "Position 4"
    - "Position 5"
    - "Activé"
    - "Désactivé"
  min_temp: 16
  max_temp: 31
  availability_template: "{{ states('switch.localtuya_integration_climatisation_salon_power') in ['on', 'off'] }}"
  current_temperature_template: "{{ states('sensor.localtuya_integration_climatisation_salon_temperature_courante') }}"
  set_hvac_mode:
    - service: automation.trigger
      data:
        skip_condition: false
      target:
        entity_id: automation.0009_climate_template_climatisation_salon_set_hvac_mode
  set_fan_mode:
    - service: automation.trigger
      data:
        skip_condition: false
      target:
        entity_id: automation.0009_climate_template_climatisation_salon_set_fan_mode
  set_swing_mode:
    - service: automation.trigger
      data:
        skip_condition: false
      target:
        entity_id: automation.0009_climate_template_climatisation_salon_set_swing_mode
  set_temperature:
    - service: automation.trigger
      data:
        skip_condition: false
      target:
        entity_id: automation.0009_climate_template_climatisation_salon_set_temperature
```
It's more clearer ?
