### ISSUE TITLE
target_humidity not specify but appear in thermostat in HA

### ISSUE THREAD

**Issue by devildant** [litinoveweedle/hass-template-climate#22]
### The problem

Hi, 
I hadn't paid attention but I have the option to define the target humidity, however I don't have this option on my air conditioner, how can I remove this option from the thermostat ha?

![image](https://github.com/litinoveweedle/hass-template-climate/assets/8700106/0a53723f-71e6-45b0-9919-79afa8ba08e6)

```
- platform: climate_template
  name: Climatisation Chambre Climate Template
  unique_id: climatisation_chambre_climate_template
  # unique id not working but mendatory for working
  icon_template: mdi:air-conditioner
  hvac_modes:
    - "dry"
    - "off"
    - "cool"
    - "fan_only"
  fan_modes:
    - "Auto"
    - "20%"
    - "40%"
    - "60%"
    - "80%"
    - "100%"
    - "Silencieux"
    - "Turbo"
  swing_modes:
    - "Position 1"
    - "Position 2"
    - "Position 3"
    - "Position 4"
    - "Position 5"
    - "Activé"
    - "Désactivé"
  min_temp: 16
  max_temp: 31
  availability_template: "{{ states('switch.localtuya_integration_climatisation_chambre_power') in ['on', 'off'] }}"
  current_temperature_template: "{{ states('sensor.localtuya_integration_climatisation_chambre_temperature_courante') }}"
  set_hvac_mode:
    - service: automation.trigger
      data:
        skip_condition: false
      target:
        entity_id: automation.0011_climate_template_climatisation_chambre_set_hvac_mode
  set_fan_mode:
    - service: automation.trigger
      data:
        skip_condition: false
      target:
        entity_id: automation.0011_climate_template_climatisation_chambre_set_fan_mode
  set_swing_mode:
    - service: automation.trigger
      data:
        skip_condition: false
      target:
        entity_id: automation.0011_climate_template_climatisation_chambre_set_swing_mode
  set_temperature:
    - service: automation.trigger
      data:
        skip_condition: false
      target:
        entity_id: automation.0011_climate_template_climatisation_chambre_set_temperature
```

### What version of Template Climate has the issue?

0.7.1

### What version of Home Assistant are you running?

2024.6.3

### What type of installation are you running?

Home Assistant OS
