### ISSUE TITLE
Target Temperature should be null in case of ATTR_HVAC_MODE == heat_cool, currently UI is broken since if switching single to dual mode since temperature is preferred over temp_high/low

### ISSUE THREAD

**Issue by Maharshi-Pathak** [litinoveweedle/hass-template-climate#24]
https://github.com/litinoveweedle/hass-template-climate/blob/0a625358d0a2843780c1f6b80f49ef1d817985bb/custom_components/climate_template/climate.py#L1587
current behavior: 
![image](https://github.com/user-attachments/assets/84211c66-f39b-4c32-b43b-7f2e7d1359cb)
expected behavior: 
![image](https://github.com/user-attachments/assets/389ef1b1-8faa-43d1-ac0e-7f89a2feb1c4)

**Comment by litinoveweedle** [comment]
Hello, thank you for the report. May I ask you for a more detailed description, together with the step by step guide to reproduce the issue?

**Comment by Maharshi-Pathak** [comment]
I am trying to create an automation that captures the current conditions of my Ecobee thermostat (via Home Assistant integration) when I turn on a conditional switch. The goal is to show non-admin users of my Home Assistant instance that these conditions are set according to their preferences, while the automation applies an energy-saving temperature delta to the setpoint.

However, I am encountering an issue with the configuration where all three attributes—target_temperature, target_temperature_high, and target_temperature_low—are set up using a template entity. When the HVAC mode is set to heat_cool, only the target_temperature is being read by the entity. This is because the input_text entity used as a template for the target_temperature attribute is null in heat_cool mode. The climate_template entity is missing a check for HVAC modes and only verifies whether the target_temperature is not None, regardless of the HVAC mode.

In real thermostats, see the Ecobee integration's set_temperature [method ](https://github.com/home-assistant/core/blob/e1e64be3c9a2597ca17f77ba1ae6c8dbb063eef3/homeassistant/components/ecobee/climate.py#L752)for proper handling of such cases.

My climate_template conf:
```
  - platform: climate_template
    unique_id: de0bf8db-b826-44e1-8911-446fdb66c7bf
    name: Smart Cities Snapshot 2
    mode_action: restart
    min_temp: 45.0
    max_temp: 95.0

    hvac_modes:
      - "heat_cool"
      - "heat"
      - "off"
      - "cool"
      - "fan_only"
    fan_modes:
      - "auto"
      - "on"
    preset_modes:
      - "away"
      - "home"
      - "sleep"
      - "away_indefinitely"
      - "temp"
    current_temperature_template: "{{ float(state_attr('climate.office', 'current_temperature'), None) }}"
    target_temperature_template: "{{ states('input_text.smart_cities_snapshot_temperature')|float(None) }}"
    target_temperature_high_template: "{{ states('input_text.smart_cities_snapshot_target_temp_high') | float(None)}}"
    target_temperature_low_template: "{{ states('input_text.smart_cities_snapshot_target_temp_low') | float(None)}}"
    hvac_mode_template: "{{ states('climate.office')}}"
    hvac_action_template: "{{ state_attr('climate.office', 'hvac_action')}}"
    fan_mode_template: "{{ states('input_text.smart_cities_snapshot_fan_mode') }}"
    preset_mode_template: "{{ states('input_text.smart_cities_snapshot_preset_mode') | lower }}"

    temp_step: 0.5
    set_temperature:
      - service: climate.set_temperature
        target:
          entity_id: climate.smart_cities_snapshot_2
        data: >
          {% if states('climate.office') in ['heat_cool']  %}
            {"target_temp_high": {{ float(state_attr('climate.smart_cities_snapshot_2', 'target_temp_high'), None) }},
            "target_temp_low": {{ float(state_attr('climate.smart_cities_snapshot_2', 'target_temp_low'), None) }} }
          {% elif states('climate.office') in ['heat', 'cool']  %}
            {"temperature": {{ float(state_attr('climate.smart_cities_snapshot_2', 'target_temperature'), None) }},
          {% else %}
            {"hvac_mode": 'Off'}
          {% endif %}

    set_hvac_mode:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.smart_cities_snapshot_2
        data:
          entity_id: climate.smart_cities_snapshot_2
          hvac_mode: "{{ states('climate.office')}}" 
```
