### ISSUE TITLE
Cannot call "set_hvac_mode" with conditions

### ISSUE THREAD

**Issue by stich86** [litinoveweedle/hass-template-climate#28]
### The problem

Hi @litinoveweedle,

i'm trying to call *set_hvac_mode* with some conditions inside, because this cliamate (managed with ModBUS) has different type of register (coil to set heat\cool mode, and holding register to on\off).

But each time I try to change mode (on\off\head\cool) got this error:

```
Mansarda: Choose at step 1: choice 2: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['value']
Mansarda: Error executing script. Invalid data for choose at pos 1: extra keys not allowed @ data['value']
```

Any hints?

Thanks!

### What version of Template Climate has the issue?

0.7.3

### What version of Home Assistant are you running?

2024.12.0

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yml
# Climate Template
climate:
 # Template termostato Mansarda
- platform: climate_template
  name: "Mansarda"
  unique_id: fancoil_mansarda
  min_temp: 16
  max_temp: 30
  precision: 0.1
  temp_step: 0.5
  hvac_modes:
    - "off"
    - "heat"
    - "cool"
  preset_modes:
    - "auto"
    - "comfort"
    - "eco"
  fan_modes:
    - "off"
    - "low"
    - "medium"
    - "high"
  # Template State
  # availability_template: "{{ states('sensor.current_pdc_status') in ['Accesa', 'Spenta'] }}"
  current_temperature_template: "{{ states('sensor.temperatura_attuale_mansarda') }}"
  target_temperature_template: "{{ states('sensor.set_point_inverno_mansarda') if states('sensor.current_pdc_mode') | int == 0 else states('sensor.set_point_estate_mansarda') }}"
  hvac_mode_template: "{{ 'off' if states('sensor.current_pdc_termostato_mansarda') == '0' else ('heat' if states('sensor.current_pdc_termostato_mansarda') == '10' and states('sensor.current_pdc_mode') == 'Inverno' else ('cool' if states('sensor.current_pdc_termostato_mansarda') == '10' and states('sensor.current_pdc_mode') == 'Estate' else 'off')) }}"
  # HVAC Action Template
  hvac_action_template: >
    {% if states('sensor.current_pdc_mode') == 'Inverno' and states('sensor.current_pdc_termostato_mansarda') == '10' %}
    heating
    {% elif states('sensor.current_pdc_mode') == 'Estate' and states('sensor.current_pdc_termostato_mansarda') == '10' %}
    cooling
    {% else %}
    off
    {% endif %}
  # FAN Mode Template
  fan_mode_template: >
    {% if is_state('sensor.auh_4_fan_speed_mode_mansarda','0') %}
    off
    {% elif is_state('sensor.auh_4_fan_speed_mode_mansarda','10') %}
    low
    {% elif is_state('sensor.auh_4_fan_speed_mode_mansarda','20') %}
    medium
    {% elif is_state('sensor.auh_4_fan_speed_mode_mansarda','30') %}
    high
    {% endif %}
  # Set Temperature 
  set_temperature:
  - service: modbus.write_register
    data:
      hub: pdc_hub
      slave: 1
      address: >
        {% if states('sensor.current_pdc_mode') == 'Inverno' %}
        46
        {% elif states('sensor.current_pdc_mode') == 'Estate' %}
        50
        {% endif %}
      value: "{{ state_attr('climate.mansarda', 'temperature') | int * 10 }}"
  # Set HVAC Mode 
  #set_hvac_mode:
  #- service: modbus.write_coil
  #  data:
  #    hub: pdc_hub
  #    slave: 1
  #    address: 0
  #    value: "{{ 0 if is_state('climate.mansarda', 'heat') else 1 }}"
  set_hvac_mode:
    - choose:
        - conditions:
            - condition: state
              entity_id: climate.mansarda
              state: 'off'
          sequence:
            - service: modbus.write_register
              data:
                hub: pdc_hub
                slave: 1
                address: 42
                value: 0
        - conditions:
            - condition: state
              entity_id: climate.mansarda
              state: 'heat'
          sequence:
            - service: modbus.write_coil
              data:
                hub: pdc_hub
                slave: 1
                address: 0
                value: 0
            - service: modbus.write_register
              data:
                hub: pdc_hub
                slave: 1
                address: 42
                value: 10
        - conditions:
            - condition: state
              entity_id: climate.mansarda
              state: 'cool'
          sequence:
            - service: modbus.write_coil
              data:
                hub: pdc_hub
                slave: 1
                address: 0
                value: 1
            - service: modbus.write_register
              data:
                hub: pdc_hub
                slave: 1
                address: 42
                value: 10    
  # Set Preset Mode 
  set_preset_mode:
  - service: modbus.write_register
    data:
      hub: pdc_hub
      slave: 1
      address: 21
      value: >
        {% if is_state_attr('climate.mansarda','preset_mode', 'auto') %}
        3
        {% elif is_state_attr('climate.mansarda','preset_mode', 'eco') %}
        1
        {% elif is_state_attr('climate.mansarda','preset_mode', 'comfort') %}
        2      
        {% endif %}      
  # Set FAN Mode
  set_fan_mode:
    - service: modbus.write_register
      data:
        hub: pdc_hub
        slave: 1
        address: 54
        value: >
          {% if is_state_attr('climate.mansarda','fan_mode', 'off') %}
          0
          {% elif is_state_attr('climate.mansarda','fan_mode', 'low') %}
          10
          {% elif is_state_attr('climate.mansarda','fan_mode', 'medium') %}
          20
          {% elif is_state_attr('climate.mansarda','fan_mode', 'high') %}
          30
          {% endif %}
```
